"""add reasoning trace to questions

Revision ID: add_reasoning_trace_001
Revises: c9ebb6bcc0ed
Create Date: 2025-01-20 20:41:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_reasoning_trace_001'
down_revision = 'c9ebb6bcc0ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('reasoning_trace', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'reasoning_trace')
    # ### end Alembic commands ###
