"""remove reasoning trace from questions

Revision ID: remove_reasoning_trace_001
Revises: add_reasoning_trace_001
Create Date: 2025-08-21 15:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_reasoning_trace_001'
down_revision = 'add_reasoning_trace_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'reasoning_trace')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('reasoning_trace', sa.Text(), nullable=True))
    # ### end Alembic commands ###
